#!/usr/bin/env python3
"""Generate toc.yml for Jupyter Book / MyST from lecture folder layout."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "toc.yml"
LECTURE_ROOTS = ("2025 Video Lectures", "2026 Video Lectures")


def folder_number(name: str) -> int:
    match = re.match(r"^(\d+)\.", name)
    return int(match.group(1)) if match else 99_999


def folder_title(name: str) -> str:
    match = re.match(r"^\d+\.\s*(.+)", name)
    return match.group(1).strip() if match else name


def yaml_quote(value: str) -> str:
    if re.search(r'[:#\[\]{}&*!|>\'"%@`]', value) or value.strip() != value:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def discover_notebooks() -> list[tuple[str, list[tuple[str, Path]]]]:
    """Return [(year_section, [(title, path), ...]), ...]."""
    sections: list[tuple[str, list[tuple[str, Path]]]] = []
    for root_name in LECTURE_ROOTS:
        root = ROOT / root_name
        if not root.is_dir():
            continue
        by_folder: dict[Path, list[Path]] = {}
        for nb in root.rglob("*.ipynb"):
            if ".ipynb_checkpoints" in nb.parts:
                continue
            by_folder.setdefault(nb.parent, []).append(nb)
        entries: list[tuple[str, Path]] = []
        for folder in sorted(by_folder, key=lambda p: (folder_number(p.name), p.name)):
            notebooks = sorted(by_folder[folder], key=lambda p: p.name.lower())
            title = folder_title(folder.name)
            for nb in notebooks:
                if len(notebooks) == 1:
                    entries.append((title, nb))
                else:
                    stem = nb.stem.replace("_", " ").replace("-", " ").title()
                    entries.append((f"{title} — {stem}", nb))
        sections.append((root_name, entries))
    return sections


def render_toc(sections: list[tuple[str, list[tuple[str, Path]]]]) -> str:
    lines = [
        "# Auto-generated by scripts/generate_toc.py — do not edit by hand.",
        "version: 1",
        "project:",
        "  toc:",
        "    - file: intro.md",
    ]
    for section_name, entries in sections:
        lines.append(f"    - title: {yaml_quote(section_name)}")
        lines.append("      children:")
        for title, path in entries:
            rel = path.relative_to(ROOT).as_posix()
            lines.append(f"        - file: {rel}")
            lines.append(f"          title: {yaml_quote(title)}")
    return "\n".join(lines) + "\n"


def main() -> None:
    sections = discover_notebooks()
    total = sum(len(e) for _, e in sections)
    OUTPUT.write_text(render_toc(sections), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({total} notebooks across {len(sections)} sections)")


if __name__ == "__main__":
    main()
